Product page
Vacannot/PinkRent pull request #31
Opened 2022-11-28 14:54 UTC by frontMAX

product page layout,
search input,
img scroll,
product card, 
blurry img

2022-11-29 02:46 UTC, Vacannot commented on src/App.tsx
> +          <Route path="NotificationPage" element={<NotificationPage />} />
Dra ner develop i din branch, tror denna routingen kommer ge conflicts även om det inte syns om vi mergerar nu!

2022-11-29 02:46 UTC, Vacannot requested changes
See comments!

2022-11-29 06:23 UTC, frontMAX commented on src/App.tsx
> +          <Route path="NotificationPage" element={<NotificationPage />} />
jag har redan gjort det innan jag gjorde en pr

2022-11-29 06:27 UTC, frontMAX commented on src/App.tsx
> +          <Route path="NotificationPage" element={<NotificationPage />} />
men ser att det ligger 2 stycken notificationPage :/

2022-11-29 07:32 UTC, Vacannot commented on src/App.tsx
> +          <Route path="NotificationPage" element={<NotificationPage />} />
:( verkar vara nå konstigt som försigår, kan kicka på det om en liten stund, nu ger den iallafall conflicts på github

2022-11-29 07:41 UTC, frontMAX commented
Kan kolla snart kan nog gissa vad de är, tog en promenad nu men snart
tillbaka

On Tue, 29 Nov 2022 at 08:32, Simon Eriksson ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/App.tsx
> <https://github.com/Vacannot/pinkrent/pull/31#discussion_r1034387259>:
>
> > @@ -14,6 +15,9 @@ function App() {
>
>        <BrowserRouter>
>
>          <Routes>
>
>            <Route path="/" element={<Layout />} />
>
> +          <Route path="NotificationPage" element={<NotificationPage />} />
>
>
> :( verkar vara nå konstigt som försigår, kan kicka på det om en liten
> stund, nu ger den iallafall conflicts på github
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Vacannot/pinkrent/pull/31#discussion_r1034387259>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVZ472CYRLORX44HFIA6PHTWKWWQ3ANCNFSM6AAAAAASNNRLHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-29 09:35 UTC, Vacannot approved these changes
Egentligen så borde Layout som ligger i pages ligga i sin egen map, samma som (((BORDE))) finnas i develop men jag fattar inte vad som händer med den, så detta fungerar la tills vidare

2022-11-29 10:13 UTC, Vacannot approved these changes

2022-11-30 10:08 UTC, fiababiakandersson approved these changes

2022-11-30 10:09 UTC, merged