Feature fia style bugs
Vacannot/PinkRent pull request #61
Opened 2022-12-05 14:47 UTC by fiababiakandersson

we will have to look into how the wave looks on bigger screen but this is a solution that works for now

closes #59

2022-12-05 23:11 UTC, Vacannot commented on src/pages/StartPage.tsx
> +      <Box
Smart!! Försökte lösa detta innan men lyckades inte!

2022-12-05 23:13 UTC, Vacannot commented on src/xxxxxxxxxx/AddProductPage.tsx
> +
Vi måste försöka bli av med hela xxxxxxxxx foldern, har tagit bort den typ 6345 gånger nu men den fortsätter komma tillbaka

2022-12-05 23:13 UTC, Vacannot requested changes
Ta bort xxxxxxxxxx foldern, annars snyggt!

2022-12-06 09:01 UTC, PettoDavida approved these changes
lgtm

2022-12-06 09:01 UTC, PettoDavida approved these changes
lgtm

2022-12-06 09:27 UTC, frontMAX approved these changes

2022-12-06 15:40 UTC, Vacannot approved these changes

2022-12-06 15:41 UTC, merged